### ISSUE TITLE
Add tests to check whether the domain portion of threads still links to the thread's target url, not the domain page

### ISSUE THREAD

**Issue by Pamasich** [Pamasich/kbin-kes#20]
Right now, threads might have a preview image and they have a title, both of which take the user to the thread's comment section.

Once inside, clicking the title or image of a link thread will open the linked page, and clicking the image of an image thread will open the image.

This addon should add a way to access the linked article directly from the threads overview, without having to first go to the comment section. But it should be done without replacing existing behavior.
Additionally, the preview image of image threads should open the image directly even from outside the comments view.

Maybe just use the preview image for both? Does every link thread have one? Try making a link thread linking to example.org as a test.

**Comment by aclist** [comment]
IIRC, the remote URL on a thread with a link does not actually resolve in the thread index, so you have to fetch the thread contents itself to get the URL, which adds a significant overhead versus typical addons that just transform the link via text replace.

**Comment by Pamasich** [comment]
Actually, I just found out that apparently the domain part next to the title links to the actual url. Interesting, I had assumed that would link to the domain's page on kbin.

This is already possible then. For now at least. I personally believe the domain link should link to the domain's page, not the article's url, so maybe either kbin or mbin changes that behavior in the future. I should write tests to check for that, leaving this issue open for now to remind me of this.

I think the overhead is a problem, but that just means the url shouldn't be computed automatically as threads load in. If I do end up implementing this, it should be done at the moment the user clicks the preview image or whatever else I'll decide to use.

**Comment by aclist** [comment]
Wow, good find...I assumed those went back to threads matching that domain, like on Reddit. This seems like weird behavior, but at least it works.

**Comment by Pamasich** [comment]
Currently planned goals:

- Add the tests

Then:

- Close this issue
