### ISSUE TITLE
Fix Github raw links

### ISSUE THREAD

**Issue by Pamasich** [Pamasich/kbin-kes#44]
Sometimes Github returns the wrong page when using its /raw/ links. Switch them to using `raw.githubusercontent.com` instead to prevent this.

Further discussed in [aclist/kbin-kes:#205](https://github.com/aclist/kbin-kes/issues/205).

**Comment by Pamasich** [comment]
Currently planned goals:

- Replace the github raw links with direct links to raw.githubusercontent.com
- Read up on whether there's any reason NOT to do this

Then:

- Close this issue if no good reason not to do this was found.
- Otherwise bring it up on the main repository and keep this issue unchanged

**Comment by aclist** [comment]
I think eventually this is going to bump into the rate limit if the number of mods exceeds about 80 (currently at about half that). Maybe we should be thinking about keeping atomic scripts as files-of-reference in the source code and accepting atomic scripts for PRs, but having a build routine that consolidates all of them into a single JS file from which the functions can be sourced at runtime. (At this point, functions would absolutely have to be private to each mod to prevent collisions, and any mods not following this would need to be refactored. Or some sort of mod function namespacing logic could be used.) This would effectively shrink the requires from N==mods to 1, plus a handful of files like the CSS.

**Comment by Pamasich** [comment]
Hmm, good argument. I'll remove it from the items I planned to do next then. Seems like there's still more planning to do with this one.

**Comment by Pamasich** [comment]
The `requires-approval` tag means that any future steps on this should be discussed first, I put it on non-minor changes to others' mods or KES in general.

Just for clarification since the name isn't too clear.

**Comment by Pamasich** [comment]
Actually, I'm not sure what I was thinking just now. I'll put it back to Planned.

Halfway through your comment I seem to have forgotten that this won't be a problem until KES gets some more mods and runs into the rate limit, so it's absolutely possible to change the links for now and worry about that after changing them, not instead of.

**Comment by Pamasich** [comment]
I should adjust the goals though.

Currently planned goals:

- Replace the github raw links with direct links to raw.githubusercontent.com
- Read up on whether there's any reason NOT to do this
- Create a new issue on the future problem that has been brought up here, both here and on the main repository

Then:

- Close this issue if no good reason not to do this was found.
- Otherwise bring it up on the main repository and keep this issue unchanged

**Comment by Pamasich** [comment]
So, I've switched all the urls over and created the pull request for it. Couldn't really find any reason not to do it online, both using search engines and AI, so I assume it's safe.

Will create the new issues tomorrow. This one will be closed when the pull request is merged.
