### ISSUE TITLE
Check for Mbin compatibility

### ISSUE THREAD

**Issue by Pamasich** [Pamasich/kbin-kes#49]
My scripts so far aren't relevant to Mbin at all, but make sure they don't break anything.

**Comment by Pamasich** [comment]
About the alt all content access, it WILL break things if it is allowed to run. Find out a way to detect mbin and prevent the addon from running if it's found. But something that ideally should be relatively easy with barely any overhead.

**Comment by Pamasich** [comment]
Also check if other mods are compatible with mbin too.

**Comment by aclist** [comment]
My naive approach so far has been to use:

`const keyw = document.querySelector('meta[name="keywords"]').content.split(',')[0]`

Unless something changes, this should resolve to either `kbin` or `mbin`.

**Comment by Pamasich** [comment]
Currently planned goals:

- Investigate if `fix-codeblocks` is needed and works on kbin.run / doesn't cause any issues
- If `fix-codeblocks` is not needed on mbin, add a corresponding comment to the mod's description
- Add a check to stop the `alt-all-content-access` mod from executing on mbin
- Add a comment to the description of `all-all-content-access` explaining it won't do anything on mbin

>

- Check other mods if they're compatible too
- If issues are found, add a note to their description and open an issue on the main KES Github, explaining the issue
- If the fix is easy, do it directly and bypass the above approach

Then:

- Keep this issue open (but move it back to Todo) if any third party mod with issues was found and not directly fixed
- Mention the created issues here
- Change the priority and effort to reflect the remaining work needed on making all of KES work with mbin

**Comment by aclist** [comment]
> My naive approach so far has been to use:
> 
> `const keyw = document.querySelector('meta[name="keywords"]').content.split(',')[0]`
> 
> Unless something changes, this should resolve to either `kbin` or `mbin`.

I've added a utility function called `getInstanceType` to the helpers that KES pulls in. It should return either `kbin` or `mbin`. Can be used by mods to conditionally support either type.

```
if (getInstanceType() == "kbin"){
    ...
}
